{% set version = '0.10-2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-xts
  version: {{ version|replace("-", "_") }}

source:
  fn: xts_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/xts_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/xts/xts_{{ version }}.tar.gz
  sha256: 8155888319c38e874ed87300decd65570e77ea4a7575136f4690123d3f7321c4

build:
  merge_build_host: True  # [win]
  number: 1
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('fortran') }}  # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed  # [win]
    - {{posix}}coreutils  # [win]
  host:
    - r-base
    - r-zoo >=1.7_12
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-zoo >=1.7_12

test:
  commands:
    - $R -e "library('xts')"           # [not win]
    - "\"%R%\" -e \"library('xts')\""  # [win]

about:
  home: https://github.com/joshuaulrich/xts
  license: GPL (>= 2)
  summary: Provide for uniform handling of R's different time-based data classes by extending
    zoo, maximizing native format information preservation and allowing for user level
    customization and extension, while simplifying cross-class interoperability.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
