travis:
  secure:
    BINSTAR_TOKEN: rdQM8nfaHslwUHWQ5l1xdgWrd86PmJv5IcG1a0JG6ax1PGZZOpaAk7gkEJ2g0SVExz9AhPosXS/Z42hC7AEFMNWuunXJ8IXFIPlsOOirbiyao9kvpnEmKFxZ42DHyDJBVbv3rbkZ5mg+Vhp/99fUig/B8/YKNWplnEI8Yx+hZK7nI4ipSd+BZLW3hPKuSD7eUFcZkukmf9iGAcJjas3tqaSVUSoTPeNks1lCvY77Eia5r7AZvl2qkdXsWiXc69mYlSe41lxPPiv0pixqjK2Qhhm1aoc7SrFZrR/SlbVt5uYmYgM9sfmEIfjfm9V0WpHEpSrlrQboTSdBDLv/g7IivO2WQQZ1vv1rsvpakbbvTR2qKxh1r/vh+Juw9YJbiqDXitTOytEmpXUH76+ez6oNF4wLI0uPklvu2rgt8U0y1px+Bd9R33188XHIyTiw3LNs6EBgoAGhWAsw1rSd9nt4TbrPJLAPOHCL4Hwr0KPABruBLUknFW6KrtwLfRyPDgc8aMtE6gYhlZGUHE3NdEIRHJ/LYs2VROuNtFVVaDsKb9jE9nKV7YBxmR7Gdpe370VPKIhnNtkMWCLTaeMF17oNvgZerkxvOueU+zlWd6kSsBPDtMgE4HY7NvEnh3jBLoYmPbdOmaIqFl41l6O9F5NaWUIVduCudjhv1IOdauU4Q6g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
